services:
  - type: web
    name: food-delivery-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn myproject.wsgi:application"
