services:
  - type: web
    name: food-delivery
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn myproject.wsgi:application
