


services:
  - type: web
    name: food-delivery-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python migrate.py
    startCommand: gunicorn myproject.wsgi:application
