services:
  - type: web
    name: food-delivery
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    autoDeploy: false
    deployHook: python migrate.py
