# Generated by Django 5.2.3 on 2025-07-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_teach'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='teach',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
