# Generated by Django 5.2.3 on 2025-07-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_userdata_delete_student_delete_teach_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='photodata',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
    ]
