# Generated by Django 5.2.4 on 2025-07-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_photodata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
