# Generated by Django 5.2.4 on 2025-07-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='tdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('data', models.IntegerField()),
                ('remark', models.IntegerField()),
            ],
        ),
    ]
