# Generated by Django 5.2.4 on 2025-07-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_tdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdata',
            name='remark',
            field=models.CharField(max_length=100),
        ),
    ]
