# Generated by Django 5.2.4 on 2025-07-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_tdata_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tdata',
            old_name='data',
            new_name='date',
        ),
    ]
