# Generated by Django 5.2.4 on 2025-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_data_tdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdata',
            name='date',
            field=models.CharField(),
        ),
    ]
