# Generated by Django 5.2.4 on 2025-07-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_tdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdata',
            name='id',
            field=models.IntegerField(auto_created=0, primary_key=True, serialize=False),
        ),
    ]
