# Generated by Django 5.2.4 on 2025-07-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_tdata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
            ],
        ),
    ]
