# Generated by Django 5.2.4 on 2025-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_itemdata_id_alter_itemdata_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
