# Generated by Django 5.2.4 on 2025-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_itemdata_id_alter_itemdata_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='item_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
