# Generated by Django 5.2.4 on 2025-07-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_itemdata_id_alter_itemdata_item_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemdata',
        ),
    ]
