# Generated by Django 5.2.4 on 2025-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_delete_itemdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemdata',
            fields=[
                ('item_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item_description', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
            ],
        ),
    ]
