# Generated by Django 5.2.4 on 2025-07-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_itemdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdata',
            fields=[
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
                ('photo', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
