# Generated by Django 5.2.4 on 2025-07-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_cartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartdata',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
