# Generated by Django 5.2.4 on 2025-07-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_cartdata_id_alter_cartdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdata',
            name='transaction',
            field=models.CharField(db_default='sdsdsijb', max_length=100),
        ),
    ]
