# Generated by Django 5.2.4 on 2025-07-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_tdata_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdata',
            name='transaction',
            field=models.CharField(max_length=100),
        ),
    ]
