# Generated by Django 5.2.4 on 2025-07-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_tdata_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartdata',
            name='item_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
