# Generated by Django 5.2.4 on 2025-07-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_remove_cartdata_id_alter_cartdata_item_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartdata',
        ),
    ]
