# Generated by Django 5.2.4 on 2025-07-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_delete_cartdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdata',
            fields=[
                ('id', models.IntegerField(auto_created=0, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
                ('photo', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
