# Generated by Django 5.2.4 on 2025-07-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_cartdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartdata',
        ),
    ]
