# Generated by Django 5.2.4 on 2025-07-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_cartdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartdata',
        ),
    ]
