# Generated by Django 5.2.4 on 2025-07-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_ordersdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersdata',
            old_name='user_name',
            new_name='item_name',
        ),
    ]
