# Generated by Django 5.2.4 on 2025-07-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_rename_user_name_ordersdata_item_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ordersdata',
        ),
    ]
