# Generated by Django 5.2.4 on 2025-07-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_ordersdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdata',
            name='order_date',
            field=models.CharField(),
        ),
    ]
