# Generated by Django 5.2.4 on 2025-07-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_alter_ordersdata_order_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ordersdata',
        ),
    ]
