# Generated by Django 5.2.4 on 2025-07-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_ordersdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersdata',
            name='user_name',
        ),
    ]
