# Generated by Django 5.2.4 on 2025-07-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_remove_ordersdata_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ordersdata',
        ),
    ]
