# Generated by Django 5.2.4 on 2025-07-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_delete_ordersdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordersdata',
            fields=[
                ('order_id', models.IntegerField(auto_created=0, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order_date', models.CharField()),
                ('request', models.CharField(max_length=100)),
            ],
        ),
    ]
